# Generated by Django 4.0.3 on 2024-08-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0002_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
