# Generated by Django 4.0.3 on 2024-08-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_delete_app_alter_payroll_employee_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll'),
        ),
    ]
