# Generated by Django 4.0.3 on 2024-08-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Services', 'Services'), ('Accounting', 'Accounting'), ('Inventory', 'Inventory'), ('Manufacturing', 'Manufacturing'), ('Human Resources', 'Human Resources')], default='Sales', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
